
import { ModuleConfig } from "@/types/module-config";

export const MODULES: ModuleConfig[] = [
  {
    id: "dispatch",
    title: "Dispatch Center",
    description: "Manage transport requests, crew assignments, and real-time tracking",
    icon: "radio",
    route: "/dispatch",
    aiEnabled: true,
    features: [
      {
        id: "active-dispatches",
        title: "Active Dispatches",
        description: "View and manage ongoing transport operations",
        route: "/dispatch",
        icon: "activity",
      },
      {
        id: "crew-assignment",
        title: "Crew Assignment",
        description: "Assign crews to transport requests with AI recommendations",
        route: "/crew",
        icon: "users",
        badge: {
          text: "AI",
          variant: "secondary",
        },
      },
      {
        id: "transport-dashboard",
        title: "Transport Dashboard",
        description: "Overview of all transport activities with analytics",
        route: "/transport-dashboard",
        icon: "layout-dashboard",
      },
      {
        id: "route-optimization",
        title: "Route Optimization",
        description: "AI-powered route planning and optimization",
        route: "/smart-route-optimization",
        icon: "route",
        badge: {
          text: "AI",
          variant: "secondary",
        },
      },
    ],
  },
  {
    id: "billing",
    title: "Billing Management",
    description: "Handle claims, insurance verification, and payment processing",
    icon: "receipt",
    route: "/billing",
    aiEnabled: true,
    features: [
      {
        id: "billing-dashboard",
        title: "Billing Dashboard",
        description: "Overview of billing status and financial metrics",
        route: "/billing",
        icon: "calculator",
      },
      {
        id: "claims-management",
        title: "Claims Management",
        description: "Process and track insurance claims",
        route: "/claims",
        icon: "file-text",
      },
      {
        id: "insurance-verification",
        title: "Insurance Verification",
        description: "Verify coverage and eligibility",
        route: "/verification-queue",
        icon: "check-circle",
      },
      {
        id: "authorization-queue",
        title: "Authorization Queue",
        description: "Manage prior authorizations with AI assistance",
        route: "/authorization-queue",
        icon: "list-checks",
        badge: {
          text: "AI",
          variant: "secondary",
        },
      },
    ],
  },
  {
    id: "supervision",
    title: "Supervision Hub",
    description: "Monitor operations, quality assurance, and compliance",
    icon: "shield",
    route: "/supervision",
    aiEnabled: true,
    features: [
      {
        id: "operations-map",
        title: "Operations Map",
        description: "Real-time visualization of fleet and crew locations",
        route: "/operations-map",
        icon: "map",
      },
      {
        id: "quality-assurance",
        title: "Quality Assurance",
        description: "Review and manage quality metrics",
        route: "/qa",
        icon: "badge-check",
      },
      {
        id: "performance",
        title: "Performance Analytics",
        description: "AI-driven insights into operational performance",
        route: "/performance",
        icon: "bar-chart",
        badge: {
          text: "AI",
          variant: "secondary",
        },
      },
      {
        id: "alerts-config",
        title: "Alerts Configuration",
        description: "Set up automated notifications and alerts",
        route: "/alerts",
        icon: "bell",
      },
    ],
  },
  {
    id: "hr",
    title: "Human Resources",
    description: "Employee management, scheduling, and certifications",
    icon: "users",
    route: "/hr",
    aiEnabled: true,
    features: [
      {
        id: "employee-directory",
        title: "Employee Directory",
        description: "View and manage employee profiles",
        route: "/hr/employees",
        icon: "contact",
      },
      {
        id: "schedule-overview",
        title: "Schedule Management",
        description: "AI-powered scheduling and shift planning",
        route: "/hr/schedule",
        icon: "calendar",
        badge: {
          text: "AI",
          variant: "secondary",
        },
      },
      {
        id: "certifications",
        title: "Certification Tracking",
        description: "Monitor credentials and license status",
        route: "/hr/certificates",
        icon: "diploma",
      },
      {
        id: "broadcast-center",
        title: "Broadcast Center",
        description: "Company announcements and communications",
        route: "/hr/announcements",
        icon: "megaphone",
      },
    ],
  },
];
