// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lajhlygctofolkxpbtgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhamhseWdjdG9mb2xreHBidGd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyNjQzMzksImV4cCI6MjA1Mjg0MDMzOX0.O9Ri-kAuwGQXO0vUfB1NcwFWzoCasV8yNaiUn5u_5MM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);